[package]
name = "oxidoc"
version = "0.1.1"
authors = ["Ruin0x11"]

[dependencies]
syntex_syntax = "0.58.1"
serde = "0.9.9"
serde_derive = "0.9.9"
bincode = "0.7.0"
serde_json = "0.9.8"
toml = "0.3"
clap = "2.20.5"
error-chain = "0.10.0"
log = "0.3"
env_logger = "0.3"
pager = "0.9.4"
regex = "0.2"